### ISSUE TITLE
Interested in new signs ?

### ISSUE THREAD

**Issue by dora71** [webdesigner97/streets#39]
Is there an interest to integrate new signs in the streets mod? I think of signs "closer to reality", like a stop sign, or speed limit signs.
Some examples are already "produced", but still need to be integrated/tested. Just want to know if there is anybody out there interested in it.

**Comment by webdesigner97** [comment]
A bigger variety of signs would be awesome! Unfortunately, I don't have any time to work on this projects at least until summer :(

**Comment by dora71** [comment]
Fortunately, you built your mod with github, so collaboration should not be the problem ;-) Will fork your mod and will see what we can do with it. I also saw an error, which I can also fix (just a wrong sign, nothing big).

To give you (or anyone else) an idea, I will enclose a picture of some signs in the signsworkshop (on my server).  Feedback welcome!

![minetest-signs](https://cloud.githubusercontent.com/assets/720694/5983329/9a5b8164-a8cc-11e4-97b0-99843e87fc0d.png)

**Comment by webdesigner97** [comment]
These are quite nice ones. They aren't perfect, but a nice start :)

Those with text on it should have a font with rougher pixels.
The railroad sign/Andreaskreuz looks a bit blurry :/
But so far, they are nice!
