### ISSUE TITLE
Problem with polemounted signs and corner pole

### ISSUE THREAD

**Issue by Thomas--S** [webdesigner97/streets#52]
![](http://i.imgur.com/D0AVjIL.png)

I think the picture explains the problem.

**Comment by Thomas--S** [comment]
Suggestion: Make the poles connected nodeboxes, that connect to group:pole and group:signs.

**Comment by webdesigner97** [comment]
We're working on it :) Connected nodeboxes are planned, but not yet on top of the todo list.

**Comment by Thomas--S** [comment]
I think I could make that changes maybe.

**Comment by webdesigner97** [comment]
You don't need to ;) We'll do this asap.

**Comment by Thomas--S** [comment]
Possible fix: #64

**Comment by cheapie** [comment]
This is not how signs are intended to be mounted.

They are intended to be mounted like this:

PS
P

Where P is a pole (either straight or heading in a different direction) and S is the sign.

**Comment by Thomas--S** [comment]
But what to do if you want to place the signs like this:

(view from top):

P S
S

e.g. when you want to mark the right of way?

**Comment by cheapie** [comment]
That's never been supported before, and I don't know if it should be, since it would require moving the signs all the way out to the edge of the node (35cm from the pole, I think).

**Comment by Thomas--S** [comment]
Or the pole connects to the sign.
Please wait for the PR update, I think I have a solution, that is fine for everyone.

**Comment by Thomas--S** [comment]
If I find time, I will rewrite the whole sign placement code. Until then, this can be closed.

**Comment by Thomas--S** [comment]
572e545
