### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by webdesigner97** [webdesigner97/streets#53]
Find suitable licenses for media/code: CC-BY-SA 3.0 seems to be fine for media, not sure which license to choose for the code though...

**Comment by benrob0329** [comment]
BSD 3 clause is basically CC-BY-SA for code.

**Comment by cheapie** [comment]
I am okay with code I've written for this project being put under the 3-clause BSD license, but I would strongly prefer the 2-clause version.

**Comment by benrob0329** [comment]
I'm curious, what's wrong with clause 3?

'''3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.'''

**Comment by cheapie** [comment]
It sounds (to me anyway) rather restrictive, almost to the point where saying things like "Yeah, my such-and-such mod is great. I based it off of webdesigner97's streets mod" would be prohibited.

There might be (and probably are) other ways to interpret that, but I don't really see the point in restricting it anyway.

Also, we'll need to get Thomas--S to weigh in on this as well, as he already has code in this repository.

Meanwhile, CC BY-SA 3.0 should be fine for the media, seeing as how the textures that we "borrowed" from infrastructure (railroad crossing and such) are under that. On that note, I'll see about putting attribution in for that once we decide on a license.

**Comment by Thomas--S** [comment]
CC BY-SA for media and BSD 2-clause for code is fine for me.

**Comment by Thomas--S** [comment]
@cheapie, @webdesigner97 Is CC BY-SA for media and BSD 2-clause for code ok for you? I think we really should add a license as soon as possible.

**Comment by cheapie** [comment]
That's fine with me.

**Comment by cheapie** [comment]
I think we're still just waiting on @webdesigner97 for this one.

**Comment by webdesigner97** [comment]
Ok, I'm back from my vacation. I'll continue my stuff tomorrow. This one is approved :)

**Comment by Thomas--S** [comment]
#83

**Comment by Thomas--S** [comment]
21e54c9
