### ISSUE TITLE
Make use of rubenwardy's achievements

### ISSUE THREAD

**Issue by webdesigner97** [webdesigner97/streets#55]

**Comment by cheapie** [comment]
This "achivevements" mod is rather obscure... are there really enough people using it that we should support it?

**Comment by Thomas--S** [comment]
I'm neutral on this one.

**Comment by webdesigner97** [comment]
I'm not quite sure anymore... It was a result of my brainstorming after my comeback to Minetest. Maybe we should gather information about the usage of @rubenwardy 's achievements and decide for a alter release.

**Comment by rubenwardy** [comment]
The mod is used in several subgames and servers, but not as popular as things like mesecons etc. It's much more of a subgame thing, related to gameplay, than a mod thing

**Comment by webdesigner97** [comment]
Ok, thank you for your quick answer!
