### ISSUE TITLE
Change Code License to MIT

### ISSUE THREAD

**Issue by Thomas--S** [webdesigner97/streets#87]
I suggest to change the code license from BSD-2-Clause to **MIT**.
Why?
* MIT License is now **commonly used in minetest_game** (as a replacement for WTFPL), so I think it would be good if the streets mod follows this example.
* MIT License and BSD-2-Clause are quite **similiar**, so I think there shouldn't be a problem.
* (I could use the code of this project in my other projects :wink:)

**More Information:**
* [MIT](http://choosealicense.com/licenses/mit/)
* [BSD-2-Clause](http://choosealicense.com/licenses/bsd-2-clause/)

**Who needs to approve this?**

- [x]  @HybridDog 
- [x]  @webdesigner97 
- [x]  @cheapie 
- [x]  @Thomas--S

**Comment by cheapie** [comment]
That's fine with me.

**Comment by Thomas--S** [comment]
Thanks, @cheapie

**Comment by webdesigner97** [comment]
Also fine for me. I wish I had more time for this project...

Von meinem Sony Xperia™-Smartphone gesendet

---- Thomas--S schrieb ----


I suggest to change the code license from BSD-2-Clause to MIT.
Why?

  *   MIT License is now commonly used in minetest_game (as a replacement for WTFPL), so I think it would be good if the streets mod follows this example.
  *   MIT License and BSD-2-Clause are quite similiar, so I think there shouldn't be a problem.
  *   (I could use the code of this project in my other projects ??)

More Information:

  *   MIT<http://choosealicense.com/licenses/mit/>
  *   BSD-2-Clause<http://choosealicense.com/licenses/bsd-2-clause/>

Who needs to approve this?

  *   @webdesigner97<https://github.com/webdesigner97>
  *   @cheapie<https://github.com/cheapie>
  *   @HybridDog<https://github.com/HybridDog>
  *   @Thomas--S<https://github.com/Thomas--S>

**Comment by Thomas--S** [comment]
Thanks, @webdesigner97

**Comment by HybridDog** [comment]
It's ok for me, too.

**Comment by Thomas--S** [comment]
Thanks, @HybridDog

**Comment by Thomas--S** [comment]
f3e8d4d
